# Tasks for Frontend Servers
- name: Install nginx on Debian
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes
# Create index.html using a template
- name: create index.html
  ansible.builtin.template:
    src: index.html.j2 # Ensure you have the file "index.html.j2" in your templates directory
    dest: /var/www/html/index.html
# Create nginx configuration file
- name: create nginx configuration
  ansible.builtin.copy:
    src: default.conf # Ensure you have the file "default.conf" in your files directory
    dest: /etc/nginx/sites-available/default
# Enable nginx configuration by creating a symlink
- name: enable nginx configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: Reload nginx